### ISSUE TITLE
Tezos website as a whole

### ISSUE THREAD

**Issue by clngr** [tqtezos/tezos.com#28]
I'm not sure if this is the right place for this, so, please advise if not.

In a direct comparison, ethereum.org offers a better approach to present information, has a better structure regarding all features, serving in a better way as a portal. Does well in showing how wide the ecosystem is. After some browsing and quickly finding precise and clear information, you hardly would think any bad of it - the outcome is positive.

If we are in the cutting edge of technology our website must offer a efficient experience focused on all possibilities and features that the Tezos network is already made of. That's the entrance of a growing world of real use cases and amazes me that the website is still, to this date, far behind from where it should be - the contents and hierarchy/structure of information doesn't show how rich the Tezos ecosystem is. For instance, we don't have on it an article for Non-fungible tokens (!) , which is present at ethereum.org; we don't have a search field, Tezos Projects are in another domain - would that be the best approach? Judging by the experiences presented on both websites, one could think less of Tezos, and we know that isn't only one getting to that conclusion.

If other chains are testnets for Tezos (and we surely are for them too) I would advise upon improving tezos.com portal to be more effective as a guidance for everyone - from newcomers to advanced devs, as they are and will always be wanted to be (and stay) with us. The future would not have room for so many different chains and talents from other teams could be welcome.

As happens for ETH and other similar chains, ours has a miriad of features and possibilities and they are not quite clear at first sight. There's a quite visible room for improvement.

[from Tezos reddit](https://www.reddit.com/r/tezos/comments/m7asmw/tezoscom_website_redesign/)

**Comment by paulo60pg** [comment]
I agree with that comment. I don't want to be rude because you've been fixing some issues lately, but the website needs a real revamp. Information and the way it is displayed needs to be rethought from scratch along with the overall design. Try to visit website like https://solana.com/ which has a very nice approach for developers and users.

Navigation is clear and easy.

![image](https://user-images.githubusercontent.com/44470174/116160111-b80b2780-a6f1-11eb-8913-5ae821b3c085.png)

Each section refers to a certain type of user. We could use the same approach. 
A developper section that would lead to a dev portal with easy to understand and well thought tutorials.
A network section that could include a with the voting system, and showing that tezos in evolving.
A community section so that user can find the right information and the right groups to communicate.
An ecosystem tab referencing the dapps build in the ecosystem.

I would be happy to help writing the information and making draft with you guys. Tezos is growing very fast now and we need a website that would not make users and developers run away from the ecosystem. The whole site needs to be rethought and redesigned. This is the showcase site of Tezos and it doesn't make you want to participate at all.

**Comment by brennancaldwell** [comment]
Thank you for your suggestions and comments; the teams are actively working on a site redesign to address a lot of the general feedback and we are excited to launch it soon. Once we are able to share more details we will do so.
